version: '3.9'
services:
  web:
    build: ./docker
    container_name: "web"
    ports:
      - "7071:7071"
    volumes:
      - .:/code
    entrypoint: sh
    command: -c "python manage.py runserver 0.0.0.0:7071"